theme: jekyll-theme-minimal
title: Katie Lamar
description: UC Berkeley EECS Masters Program
logo: logo.jpeg
show_downloads: false
google_analytics: G-ZP285X4LJM
markdown: kramdown
permalink: pretty

