theme: jekyll-theme-minimal
title: Katie Lamar
description: UC Berkeley EECS Masters Program
logo:
  src: https://i.imgur.com/qA33fQk.jpg
  alt: 18F
  external: true
show_downloads: false
google_analytics: G-ZP285X4LJM
markdown: kramdown
permalink: pretty

