theme: jekyll-theme-minimal
title: Katie Lamar
description: UC Berkeley EECS Masters Program
logo:
  src: https://www.facebook.com/photo/?fbid=2367690293244502&set=a.159725184041035
  alt: 18F
  external: true
show_downloads: false
google_analytics: G-ZP285X4LJM
markdown: kramdown
permalink: pretty

