theme: jekyll-theme-minimal
title: Katie Lamar
description: UC San Diego Bioengineering Doctoral Student| Sloan Scholar Fellow
logo: https://i.imgur.com/qA33fQk.jpg
show_downloads: false
google_analytics: G-ZP285X4LJM
markdown: kramdown
permalink: pretty

